### ISSUE TITLE
Unrecognized option 'cv'

### ISSUE THREAD

**Issue by WeissbrotDE** [meh7an/TelegramVideoStickerMaker#1]
Unrecognized option 'cv'.
Error splitting the argument list: Option not found
All videos are converted to stickers.

I get this print every time I run the script and get no output.

**Comment by meh7an** [comment]
@WeissbrotDE Try -vcodec instead of -c:v inside the code.
Your FFMPEG version may have dropped -c:v option.

**Comment by WeissbrotDE** [comment]
Thank you very much! Works fine now, thank you.

**Comment by meh7an** [comment]
@WeissbrotDE You’re welcome.
